@startuml
class Auto{
    -String nameManufaturer;
    -String nameModel;
    -int yearModel;
    -String color;
    -int km;
    -int noPassanger;
    -double price;
    -int numDoors;
}

class Puertas{
}

class Transmision{
    -String typeTransmision;
}

class Ventanas{
    -String typeWindow;
    +addWindow();
}
class Llantas{
    -double diameter;
}

class Motor{
    -String typeGas;
    -double potencia;
    +startEngine();
    +stopEngine();
}
class Concesionaria{
    -String nameConcesionaria;
    -Mecanico[] listMecanics;
    -Vendedor[] listVendedor;
    -Auto[] ListVehicles;
    +fixVehicle(Auto);
    +sellVehicle(Auto);
    +acquireVehicle();
    +scheduleService(Conductor);
}

class Mecanico{
    +repair();
    +giveService();
}
class Vendedor{
    +Sell();
}
class Conductor{
    -Drive();
    -buyCar();
}
class Pasajero{
    -String license;
}
class Persona{
    -String name;
    -int age;
    +getName();
}
Auto <--* Ventanas: son parte
Auto <--* Motor: compone
Auto <--* Puertas: compone
Auto <--* Llantas: compone
Auto <--* Transmision:compone

Persona <|-- Pasajero: hereda
Persona <|-- Mecanico: hereda
Persona <|-- Vendedor: hereda
Persona <|-- Conductor: hereda

Concesionaria <--o Mecanico: agrega
Concesionaria <--o Vendedor: agrega
Concesionaria <--o Auto: agrega
Auto <--o Conductor: agrega

Transmision--Motor: asosciado
Conductor--Pasajero: asociado
Auto--Pasajero: asociado
Concesionaria--Conductor: asociado
@enduml